openapi: 3.0.0
info:
  title: API
  description: API for social network
  version: 0.0.1
servers:
  - url: api/v1
paths:
  /task/{taskId}/comments:
    get:
      summary: получить комменты (их может быть очень много)
      parameters:
        - name: taskId
          in: path
          required: true
          description: id задачи
          schema:
            type: integer
        - name: page
          in: query
          required: true
          description: страница
          schema:
            type: integer
      responses:
        '200':
          description: '{[комментарии], предыдущая страница, следующая  страница, число записей}'

    post:
      summary: создать коммент
      parameters:
        - name: taskId
          in: path
          required: true
          description: id задачи
          schema:
            type: integer
        - name: userId
          in: query
          required: true
          description: id юзера
          schema:
            type: integer
        - name: text
          in: query
          required: true
          description: текст комментария
          schema:
            type: string

      responses:
        '200':
          description: '{id комментария}'

  /task/{taskId}/comments/{commentId}/reaction:
    post:
      summary: реакция на коммент
      parameters:
        - name: taskId
          in: path
          required: true
          description: id задачи
          schema:
            type: integer
        - name: commentId
          in: path
          required: true
          description: id комментария
          schema:
            type: integer
        - name: userId
          in: query
          required: true
          description: id юзера
          schema:
            type: integer
        - name: reaction_name
          in: query
          required: true
          description: реакция
          schema:
            type: string

      responses:
        '200':
          description: '{id объекта реакции}'

  /task/{taskId}/comments/{commentId}/reply:
    post:
      summary: ответ на коммент
      parameters:
        - name: taskId
          in: path
          required: true
          description: id задачи
          schema:
            type: integer
        - name: commentId
          in: path
          required: true
          description: id комментария
          schema:
            type: integer
        - name: userId
          in: query
          required: true
          description: id юзера
          schema:
            type: integer
        - name: text
          in: query
          required: true
          description: текст ответа
          schema:
            type: string

      responses:
        '200':
          description: '{id объекта ответа на коммент}'

    patch:
      summary: изменить ответ на коммент
      parameters:
        - name: taskId
          in: path
          required: true
          description: id задачи
          schema:
            type: integer
        - name: commentId
          in: path
          required: true
          description: id комментария
          schema:
            type: integer
        - name: userId
          in: query
          required: true
          description: id юзера
          schema:
            type: integer
        - name: text
          in: query
          required: true
          description: текст ответа
          schema:
            type: string

      responses:
        '200':
          description: '{id объекта ответа на коммент}'
